#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


def _sanitize_crate_name(op_id: str) -> str:
    # Cargo crate names are fairly permissive, but we keep it conservative.
    name = re.sub(r"[^a-zA-Z0-9_]", "_", op_id.strip())
    name = name.lower().strip("_")
    if not name:
        name = "omega_native_op"
    if len(name) > 48:
        name = name[:48]
    return f"omega_native_{name}"


def generate_fnv1a64_cdylib(*, op_id: str, out_dir: Path) -> dict[str, Any]:
    op_id = str(op_id).strip()
    if not op_id:
        raise RuntimeError("SCHEMA_FAIL")
    crate_name = _sanitize_crate_name(op_id)
    out_dir = out_dir.resolve()
    (out_dir / "src").mkdir(parents=True, exist_ok=True)

    cargo_toml = "\n".join(
        [
            "[package]",
            f'name = "{crate_name}"',
            "version = \"0.1.0\"",
            "edition = \"2021\"",
            "",
            "[lib]",
            "crate-type = [\"cdylib\"]",
            "",
            "[profile.release]",
            "codegen-units = 1",
            "lto = false",
            "debug = 0",
            "",
        ]
    )
    (out_dir / "Cargo.toml").write_text(cargo_toml + "\n", encoding="utf-8")

    # Deterministic lockfile even with no deps.
    lock = "\n".join(
        [
            "# This file is automatically @generated by Cargo.",
            "# It is not intended for manual editing.",
            "version = 3",
            "",
            "[[package]]",
            f'name = "{crate_name}"',
            'version = "0.1.0"',
            "",
        ]
    )
    (out_dir / "Cargo.lock").write_text(lock, encoding="utf-8")

    lib_rs = f"""\
use std::panic::{{catch_unwind, AssertUnwindSafe}};

const ABI_VERSION: u32 = 1;
const OP_ID: &str = "{op_id}";

fn fnv1a64(data: &[u8]) -> u64 {{
    let mut h: u64 = 0xcbf29ce484222325;
    for b in data {{
        h ^= *b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }}
    h
}}

fn parse_bloblist_v1(input: &[u8]) -> Result<Vec<&[u8]>, i32> {{
    if input.len() < 4 {{
        return Err(-2);
    }}
    let argc = u32::from_le_bytes([input[0], input[1], input[2], input[3]]) as usize;
    let lens_bytes = 4usize.checked_add(argc.checked_mul(4).ok_or(-2)?).ok_or(-2)?;
    if input.len() < lens_bytes {{
        return Err(-2);
    }}
    let mut lens: Vec<usize> = Vec::with_capacity(argc);
    let mut off = 4usize;
    for _ in 0..argc {{
        let len = u32::from_le_bytes([input[off], input[off + 1], input[off + 2], input[off + 3]]) as usize;
        lens.push(len);
        off += 4;
    }}
    let mut argv: Vec<&[u8]> = Vec::with_capacity(argc);
    for len in lens {{
        let next = off.checked_add(len).ok_or(-2)?;
        if next > input.len() {{
            return Err(-2);
        }}
        argv.push(&input[off..next]);
        off = next;
    }}
    if off != input.len() {{
        return Err(-2);
    }}
    Ok(argv)
}}

#[no_mangle]
pub extern "C" fn omega_native_abi_version() -> u32 {{
    ABI_VERSION
}}

#[no_mangle]
pub extern "C" fn omega_native_op_id_v1(out_ptr: *mut u8, out_cap: usize) -> isize {{
    let bytes = OP_ID.as_bytes();
    if out_ptr.is_null() || out_cap == 0 {{
        return bytes.len() as isize;
    }}
    if out_cap < bytes.len() {{
        return -1;
    }}
    // Minimal FFI surface: bounded memcpy into caller buffer.
    unsafe {{
        std::ptr::copy_nonoverlapping(bytes.as_ptr(), out_ptr, bytes.len());
    }}
    bytes.len() as isize
}}

#[no_mangle]
pub extern "C" fn omega_native_invoke_bloblist_v1(
    in_ptr: *const u8,
    in_len: usize,
    out_ptr: *mut u8,
    out_cap: usize,
) -> isize {{
    let work = || -> Result<Vec<u8>, i32> {{
        if in_ptr.is_null() {{
            return Err(-2);
        }}
        // Minimal FFI surface: view caller bytes.
        let input: &[u8] = unsafe {{ std::slice::from_raw_parts(in_ptr, in_len) }};
        let argv = parse_bloblist_v1(input)?;
        if argv.len() != 1 {{
            return Err(-2);
        }}
        let h = fnv1a64(argv[0]);
        Ok(h.to_le_bytes().to_vec())
    }};
    let res = catch_unwind(AssertUnwindSafe(work));
    let out = match res {{
        Ok(Ok(buf)) => buf,
        Ok(Err(code)) => return code as isize,
        Err(_) => return -3,
    }};
    if out_ptr.is_null() || out_cap == 0 {{
        return out.len() as isize;
    }}
    if out_cap < out.len() {{
        return -1;
    }}
    unsafe {{
        std::ptr::copy_nonoverlapping(out.as_ptr(), out_ptr, out.len());
    }}
    out.len() as isize
}}
"""
    (out_dir / "src" / "lib.rs").write_text(lib_rs, encoding="utf-8")

    return {"crate_name": crate_name, "op_id": op_id}


def generate_kernel_canon_bytes_cdylib(*, op_id: str, out_dir: Path) -> dict[str, Any]:
    """Generate a cdylib implementing omega_kernel_canon_bytes_v1.

    Input: 1 arg = raw JSON bytes (UTF-8).
    Output: GCJ-1 canonical JSON bytes (UTF-8, no trailing newline).
    """

    op_id = str(op_id).strip()
    if not op_id:
        raise RuntimeError("SCHEMA_FAIL")
    crate_name = _sanitize_crate_name(op_id)
    out_dir = out_dir.resolve()
    (out_dir / "src").mkdir(parents=True, exist_ok=True)

    cargo_toml = "\n".join(
        [
            "[package]",
            f'name = "{crate_name}"',
            "version = \"0.1.0\"",
            "edition = \"2021\"",
            "",
            "[lib]",
            "crate-type = [\"cdylib\"]",
            "",
            "[profile.release]",
            "codegen-units = 1",
            "lto = false",
            "debug = 0",
            "",
        ]
    )
    (out_dir / "Cargo.toml").write_text(cargo_toml + "\n", encoding="utf-8")

    # Deterministic lockfile even with no deps.
    lock = "\n".join(
        [
            "# This file is automatically @generated by Cargo.",
            "# It is not intended for manual editing.",
            "version = 3",
            "",
            "[[package]]",
            f'name = "{crate_name}"',
            'version = "0.1.0"',
            "",
        ]
    )
    (out_dir / "Cargo.lock").write_text(lock, encoding="utf-8")

    op_id_escaped = op_id.replace("\\", "\\\\").replace('"', '\\"')
    lib_rs = r"""
use std::collections::BTreeMap;
use std::fmt;
use std::panic::{catch_unwind, AssertUnwindSafe};

const ABI_VERSION: u32 = 1;
const OP_ID: &str = "__OP_ID__";

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum GcjValue {
    Null,
    Bool(bool),
    Int(i64),
    Str(String),
    Array(Vec<GcjValue>),
    Object(BTreeMap<String, GcjValue>),
}

#[derive(Debug)]
pub enum GcjError {
    Parse(String),
}

impl fmt::Display for GcjError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            GcjError::Parse(msg) => write!(f, "{msg}"),
        }
    }
}

pub fn parse_gcj(bytes: &[u8]) -> Result<GcjValue, GcjError> {
    let mut parser = Parser::new(bytes);
    let value = parser.parse_value()?;
    parser.skip_ws();
    if parser.idx != parser.bytes.len() {
        return Err(GcjError::Parse("trailing data".to_string()));
    }
    Ok(value)
}

pub fn canonical_bytes(value: &GcjValue) -> Vec<u8> {
    let mut out = String::new();
    write_canonical(value, &mut out);
    out.into_bytes()
}

pub fn canonicalize_bytes(raw: &[u8]) -> Result<Vec<u8>, GcjError> {
    let value = parse_gcj(raw)?;
    Ok(canonical_bytes(&value))
}

fn write_canonical(value: &GcjValue, out: &mut String) {
    match value {
        GcjValue::Null => out.push_str("null"),
        GcjValue::Bool(true) => out.push_str("true"),
        GcjValue::Bool(false) => out.push_str("false"),
        GcjValue::Int(i) => out.push_str(&i.to_string()),
        GcjValue::Str(s) => write_string(s, out),
        GcjValue::Array(items) => {
            out.push('[');
            for (idx, item) in items.iter().enumerate() {
                if idx > 0 {
                    out.push(',');
                }
                write_canonical(item, out);
            }
            out.push(']');
        }
        GcjValue::Object(map) => {
            out.push('{');
            for (idx, (k, v)) in map.iter().enumerate() {
                if idx > 0 {
                    out.push(',');
                }
                write_string(k, out);
                out.push(':');
                write_canonical(v, out);
            }
            out.push('}');
        }
    }
}

fn write_string(value: &str, out: &mut String) {
    out.push('"');
    for c in value.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\u{08}' => out.push_str("\\b"),
            '\u{0C}' => out.push_str("\\f"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            _ => out.push(c),
        }
    }
    out.push('"');
}

struct Parser<'a> {
    bytes: &'a [u8],
    idx: usize,
}

impl<'a> Parser<'a> {
    fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, idx: 0 }
    }

    fn parse_value(&mut self) -> Result<GcjValue, GcjError> {
        self.skip_ws();
        match self.peek() {
            Some(b'n') => self.parse_null(),
            Some(b't') | Some(b'f') => self.parse_bool(),
            Some(b'"') => self.parse_string().map(GcjValue::Str),
            Some(b'{') => self.parse_object(),
            Some(b'[') => self.parse_array(),
            Some(b'-') | Some(b'0'..=b'9') => self.parse_number(),
            Some(other) => Err(GcjError::Parse(format!("unexpected byte: {other}"))),
            None => Err(GcjError::Parse("unexpected end of input".to_string())),
        }
    }

    fn parse_null(&mut self) -> Result<GcjValue, GcjError> {
        if self.consume_literal(b"null") {
            Ok(GcjValue::Null)
        } else {
            Err(GcjError::Parse("invalid literal".to_string()))
        }
    }

    fn parse_bool(&mut self) -> Result<GcjValue, GcjError> {
        if self.consume_literal(b"true") {
            Ok(GcjValue::Bool(true))
        } else if self.consume_literal(b"false") {
            Ok(GcjValue::Bool(false))
        } else {
            Err(GcjError::Parse("invalid literal".to_string()))
        }
    }

    fn parse_string(&mut self) -> Result<String, GcjError> {
        self.expect_byte(b'"')?;
        let mut buf = Vec::new();
        loop {
            let b = self.next_byte().ok_or_else(|| GcjError::Parse("unterminated string".to_string()))?;
            match b {
                b'"' => break,
                b'\\' => {
                    let esc = self.next_byte().ok_or_else(|| GcjError::Parse("unterminated escape".to_string()))?;
                    match esc {
                        b'"' => buf.push(b'"'),
                        b'\\' => buf.push(b'\\'),
                        b'/' => buf.push(b'/'),
                        b'b' => buf.push(0x08),
                        b'f' => buf.push(0x0C),
                        b'n' => buf.push(b'\n'),
                        b'r' => buf.push(b'\r'),
                        b't' => buf.push(b'\t'),
                        b'u' => {
                            let cp = self.parse_hex4()?;
                            if (0xD800..=0xDBFF).contains(&cp) {
                                self.expect_byte(b'\\')?;
                                self.expect_byte(b'u')?;
                                let low = self.parse_hex4()?;
                                if !(0xDC00..=0xDFFF).contains(&low) {
                                    return Err(GcjError::Parse("invalid surrogate pair".to_string()));
                                }
                                let high_ten = (cp as u32 - 0xD800) << 10;
                                let low_ten = low as u32 - 0xDC00;
                                let scalar = 0x10000 + (high_ten | low_ten);
                                let ch = char::from_u32(scalar).ok_or_else(|| GcjError::Parse("invalid codepoint".to_string()))?;
                                let mut tmp = [0u8; 4];
                                buf.extend_from_slice(ch.encode_utf8(&mut tmp).as_bytes());
                            } else if (0xDC00..=0xDFFF).contains(&cp) {
                                return Err(GcjError::Parse("invalid surrogate".to_string()));
                            } else {
                                let ch = char::from_u32(cp as u32).ok_or_else(|| GcjError::Parse("invalid codepoint".to_string()))?;
                                let mut tmp = [0u8; 4];
                                buf.extend_from_slice(ch.encode_utf8(&mut tmp).as_bytes());
                            }
                        }
                        _ => return Err(GcjError::Parse("invalid escape".to_string())),
                    }
                }
                0x00..=0x1F => return Err(GcjError::Parse("control character in string".to_string())),
                _ => buf.push(b),
            }
        }
        String::from_utf8(buf).map_err(|_| GcjError::Parse("invalid utf-8".to_string()))
    }

    fn parse_array(&mut self) -> Result<GcjValue, GcjError> {
        self.expect_byte(b'[')?;
        let mut items = Vec::new();
        self.skip_ws();
        if self.peek() == Some(b']') {
            self.idx += 1;
            return Ok(GcjValue::Array(items));
        }
        loop {
            let value = self.parse_value()?;
            items.push(value);
            self.skip_ws();
            match self.next_byte() {
                Some(b',') => continue,
                Some(b']') => break,
                _ => return Err(GcjError::Parse("expected ',' or ']'".to_string())),
            }
        }
        Ok(GcjValue::Array(items))
    }

    fn parse_object(&mut self) -> Result<GcjValue, GcjError> {
        self.expect_byte(b'{')?;
        let mut map = BTreeMap::new();
        self.skip_ws();
        if self.peek() == Some(b'}') {
            self.idx += 1;
            return Ok(GcjValue::Object(map));
        }
        loop {
            self.skip_ws();
            let key = self.parse_string()?;
            if map.contains_key(&key) {
                return Err(GcjError::Parse("duplicate object key".to_string()));
            }
            self.skip_ws();
            self.expect_byte(b':')?;
            let value = self.parse_value()?;
            map.insert(key, value);
            self.skip_ws();
            match self.next_byte() {
                Some(b',') => continue,
                Some(b'}') => break,
                _ => return Err(GcjError::Parse("expected ',' or '}'".to_string())),
            }
        }
        Ok(GcjValue::Object(map))
    }

    fn parse_number(&mut self) -> Result<GcjValue, GcjError> {
        let start = self.idx;
        let mut negative = false;
        if self.peek() == Some(b'-') {
            negative = true;
            self.idx += 1;
        }
        let first = self.peek().ok_or_else(|| GcjError::Parse("invalid number".to_string()))?;
        if !matches!(first, b'0'..=b'9') {
            return Err(GcjError::Parse("invalid number".to_string()));
        }
        if first == b'0' {
            self.idx += 1;
            if matches!(self.peek(), Some(b'0'..=b'9')) {
                return Err(GcjError::Parse("leading zero".to_string()));
            }
        } else {
            while matches!(self.peek(), Some(b'0'..=b'9')) {
                self.idx += 1;
            }
        }
        let end = self.idx;
        if matches!(self.peek(), Some(b'.') | Some(b'e') | Some(b'E') | Some(b'+')) {
            return Err(GcjError::Parse("non-integer number".to_string()));
        }
        let s = std::str::from_utf8(&self.bytes[start..end]).map_err(|_| GcjError::Parse("invalid number".to_string()))?;
        let mut value: i128 = 0;
        for b in s.as_bytes() {
            if *b == b'-' {
                continue;
            }
            value = value * 10 + (b - b'0') as i128;
            if value > i64::MAX as i128 + 1 {
                return Err(GcjError::Parse("integer overflow".to_string()));
            }
        }
        if negative {
            value = -value;
        }
        if value < i64::MIN as i128 || value > i64::MAX as i128 {
            return Err(GcjError::Parse("integer overflow".to_string()));
        }
        Ok(GcjValue::Int(value as i64))
    }

    fn parse_hex4(&mut self) -> Result<u16, GcjError> {
        let mut val: u16 = 0;
        for _ in 0..4 {
            let b = self.next_byte().ok_or_else(|| GcjError::Parse("unterminated unicode escape".to_string()))?;
            val = (val << 4) | match b {
                b'0'..=b'9' => (b - b'0') as u16,
                b'a'..=b'f' => (10 + (b - b'a')) as u16,
                b'A'..=b'F' => (10 + (b - b'A')) as u16,
                _ => return Err(GcjError::Parse("invalid unicode escape".to_string())),
            };
        }
        Ok(val)
    }

    fn consume_literal(&mut self, literal: &[u8]) -> bool {
        if self.bytes.len() >= self.idx + literal.len() && &self.bytes[self.idx..self.idx + literal.len()] == literal {
            self.idx += literal.len();
            true
        } else {
            false
        }
    }

    fn skip_ws(&mut self) {
        while let Some(b) = self.peek() {
            if matches!(b, b' ' | b'\n' | b'\r' | b'\t') {
                self.idx += 1;
            } else {
                break;
            }
        }
    }

    fn expect_byte(&mut self, expected: u8) -> Result<(), GcjError> {
        match self.next_byte() {
            Some(b) if b == expected => Ok(()),
            _ => Err(GcjError::Parse("unexpected byte".to_string())),
        }
    }

    fn peek(&self) -> Option<u8> {
        self.bytes.get(self.idx).copied()
    }

    fn next_byte(&mut self) -> Option<u8> {
        let b = self.bytes.get(self.idx).copied();
        if b.is_some() {
            self.idx += 1;
        }
        b
    }
}

fn parse_bloblist_v1(input: &[u8]) -> Result<Vec<&[u8]>, i32> {
    if input.len() < 4 {
        return Err(-2);
    }
    let argc = u32::from_le_bytes([input[0], input[1], input[2], input[3]]) as usize;
    let lens_bytes = 4usize.checked_add(argc.checked_mul(4).ok_or(-2)?).ok_or(-2)?;
    if input.len() < lens_bytes {
        return Err(-2);
    }
    let mut lens: Vec<usize> = Vec::with_capacity(argc);
    let mut off = 4usize;
    for _ in 0..argc {
        let len = u32::from_le_bytes([input[off], input[off + 1], input[off + 2], input[off + 3]]) as usize;
        lens.push(len);
        off += 4;
    }
    let mut argv: Vec<&[u8]> = Vec::with_capacity(argc);
    for len in lens {
        let next = off.checked_add(len).ok_or(-2)?;
        if next > input.len() {
            return Err(-2);
        }
        argv.push(&input[off..next]);
        off = next;
    }
    if off != input.len() {
        return Err(-2);
    }
    Ok(argv)
}

#[no_mangle]
pub extern "C" fn omega_native_abi_version() -> u32 {
    ABI_VERSION
}

#[no_mangle]
pub extern "C" fn omega_native_op_id_v1(out_ptr: *mut u8, out_cap: usize) -> isize {
    let bytes = OP_ID.as_bytes();
    if out_ptr.is_null() || out_cap == 0 {
        return bytes.len() as isize;
    }
    if out_cap < bytes.len() {
        return -1;
    }
    // Minimal FFI surface: bounded memcpy into caller buffer.
    unsafe {
        std::ptr::copy_nonoverlapping(bytes.as_ptr(), out_ptr, bytes.len());
    }
    bytes.len() as isize
}

#[no_mangle]
pub extern "C" fn omega_native_invoke_bloblist_v1(
    in_ptr: *const u8,
    in_len: usize,
    out_ptr: *mut u8,
    out_cap: usize,
) -> isize {
    let work = || -> Result<Vec<u8>, i32> {
        if in_ptr.is_null() {
            return Err(-2);
        }
        // Minimal FFI surface: view caller bytes.
        let input: &[u8] = unsafe { std::slice::from_raw_parts(in_ptr, in_len) };
        let argv = parse_bloblist_v1(input)?;
        if argv.len() != 1 {
            return Err(-2);
        }
        let out = canonicalize_bytes(argv[0]).map_err(|_| -2)?;
        Ok(out)
    };
    let res = catch_unwind(AssertUnwindSafe(work));
    let out = match res {
        Ok(Ok(buf)) => buf,
        Ok(Err(code)) => return code as isize,
        Err(_) => return -3,
    };
    if out_ptr.is_null() || out_cap == 0 {
        return out.len() as isize;
    }
    if out_cap < out.len() {
        return -1;
    }
    unsafe {
        std::ptr::copy_nonoverlapping(out.as_ptr(), out_ptr, out.len());
    }
    out.len() as isize
}
""".replace("__OP_ID__", op_id_escaped).lstrip("\n")
    (out_dir / "src" / "lib.rs").write_text(lib_rs, encoding="utf-8")

    return {"crate_name": crate_name, "op_id": op_id}


def generate_cdylib(*, op_id: str, out_dir: Path) -> dict[str, Any]:
    op_id = str(op_id).strip()
    if op_id == "omega_demo_fnv1a64_v1":
        return generate_fnv1a64_cdylib(op_id=op_id, out_dir=out_dir)
    if op_id == "omega_kernel_canon_bytes_v1":
        return generate_kernel_canon_bytes_cdylib(op_id=op_id, out_dir=out_dir)
    raise RuntimeError("UNKNOWN_OP")


def main() -> None:
    ap = argparse.ArgumentParser(prog="rust_codegen_v1")
    ap.add_argument("--op_id", required=True)
    ap.add_argument("--out_dir", required=True)
    args = ap.parse_args()

    meta = generate_cdylib(op_id=str(args.op_id), out_dir=Path(args.out_dir))
    print(json.dumps({"status": "OK", **meta}, separators=(",", ":")))


if __name__ == "__main__":
    main()
