pub const R0_FILTER_ENABLED: &str = "R0_FILTER_ENABLED";
pub const R1_FILTER_COOLDOWN: &str = "R1_FILTER_COOLDOWN";
pub const R2_BUDGET_HARD_STOP: &str = "R2_BUDGET_HARD_STOP";
pub const R3_BUDGET_MIN_REMAINING: &str = "R3_BUDGET_MIN_REMAINING";
pub const R4_FILTER_COST_MAX: &str = "R4_FILTER_COST_MAX";
pub const R5_SCORE_PRIORITY: &str = "R5_SCORE_PRIORITY";
pub const R6_TIEBREAK: &str = "R6_TIEBREAK";
