NULL_BUNDLE_HASH = "0" * 64

ACTIVE_DIRNAME = "active"
LOCK_FILENAME = "LOCK"
ACTIVE_BUNDLE_FILENAME = "ACTIVE_BUNDLE"
PREV_ACTIVE_BUNDLE_FILENAME = "PREV_ACTIVE_BUNDLE"
ACTIVE_NEXT_BUNDLE_FILENAME = "ACTIVE_NEXT_BUNDLE"

LEDGER_DIRNAME = "ledger"
LEDGER_LOG_FILENAME = "ledger.log"

STAGE_DIRNAME = "stage"
STAGE_BUNDLES_DIRNAME = "bundles"

STORE_DIRNAME = "store"
STORE_BUNDLES_DIRNAME = "bundles"

KERNEL_HASH_FILENAME = "KERNEL_HASH"
META_HASH_RELATIVE_PATH = "meta_constitution/v1/META_HASH"

RECEIPT_FILENAME = "kernel_receipt.json"

FAILPOINT_ENV = "META_CORE_FAILPOINT"
FAILPOINT_AFTER_PREV_WRITE = "AFTER_PREV_WRITE"
FAILPOINT_AFTER_NEXT_WRITE = "AFTER_NEXT_WRITE"
